-- MySQL Script generated by MySQL Workbench
-- Thu Oct 30 10:09:49 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema explore_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema explore_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `explore_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `explore_db`;


-- -----------------------------------------------------
-- Table `explore_db`.`destination`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `explore_db`.`destination` ;

CREATE TABLE IF NOT EXISTS `explore_db`.`destination` (
  `destination_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `location` VARCHAR(150) NULL DEFAULT NULL,
  `image_url` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`destination_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;



-- -----------------------------------------------------
-- Table `explore_db`.`accommodation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `explore_db`.`accommodation` ;

CREATE TABLE IF NOT EXISTS `explore_db`.`accommodation` (
  `accommodation_id` INT NOT NULL AUTO_INCREMENT,
  `destination_id` INT NOT NULL,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `type` VARCHAR(50) NULL DEFAULT NULL,
  `price_per_night` DECIMAL(10,2) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `image_url` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`accommodation_id`),
  INDEX `destination_id` (`destination_id` ASC) VISIBLE,
  CONSTRAINT `accommodation_ibfk_1`
    FOREIGN KEY (`destination_id`)
    REFERENCES `explore_db`.`destination` (`destination_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;



-- -----------------------------------------------------
-- Table `explore_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `explore_db`.`user` ;

CREATE TABLE IF NOT EXISTS `explore_db`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(150) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `date_joined` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `explore_db`.`booking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `explore_db`.`booking` ;

CREATE TABLE IF NOT EXISTS `explore_db`.`booking` (
  `booking_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `accommodation_id` INT NOT NULL,
  `check_in` DATE NULL DEFAULT NULL,
  `check_out` DATE NULL DEFAULT NULL,
  `total_price` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`booking_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `accommodation_id` (`accommodation_id` ASC) VISIBLE,
  CONSTRAINT `booking_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `explore_db`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `booking_ibfk_2`
    FOREIGN KEY (`accommodation_id`)
    REFERENCES `explore_db`.`accommodation` (`accommodation_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `explore_db`.`review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `explore_db`.`review` ;

CREATE TABLE IF NOT EXISTS `explore_db`.`review` (
  `review_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `destination_id` INT NOT NULL,
  `rating` INT NULL DEFAULT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  `date_posted` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`review_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `destination_id` (`destination_id` ASC) VISIBLE,
  CONSTRAINT `review_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `explore_db`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `review_ibfk_2`
    FOREIGN KEY (`destination_id`)
    REFERENCES `explore_db`.`destination` (`destination_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
